services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Brunei123
      POSTGRES_DB: db
    volumes:
      - singlepoint_db_data:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  singlepoint_db_data:


networks:
  internal:
    name: internal_network
